// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';


console.log("LEO     ___       ");

console.log("    ___|___|       ");

console.log("    O     O       ");

console.log("___________________________");

console.log(" | | | | | | | | | | | | | ");

console.log(" | | | | | | | | | | | | | ");

console.log(" | | | | | | | | | | | | | ");

/*  Not a pure module */
